source 'http://rubygems.org'

gem "rails", "~> 3.0.0"
gem 'unicorn', '3.1.0'
gem 'blocks', :path => '..' 
gem 'mysql2'

group :development, :test do
  gem "rspec-rails", ">= 2.0.0.beta.20"
  gem 'factory_girl_rails'
  gem 'webrat'
  gem 'mocha'
  gem 'ZenTest'
  gem 'autotest-rails'
  gem 'autotest-growl'
end
